apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-uploads-pvc
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
    purpose: file-uploads
    {{- include "gestion-produits.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
