apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "gestion-produits.labels" . | nindent 4 }}
data:
  custom.cnf: |
    {{- .Values.db.configuration | nindent 4 }}
