apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: gestion-produits
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi