# Default values for gestion-produits

# Namespace configuration
namespace: gestion-produits

# Image configuration
app:
  image:
    repository: registry.germainleignel.com/library/gestion-produits
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      memory: "256Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "200m"
  # App healthcheck configuration
  healthcheck:
    enabled: true
    livenessProbe:
      path: /index.php
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      path: /index.php
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    startupProbe:
      path: /index.php
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 12  # Allow 2 minutes (12 * 10s) for startup

appMigrations:
  image:
    repository: registry.germainleignel.com/library/gestion-produits-migrations
    tag: latest

appUploads:
  image:
    repository: registry.germainleignel.com/library/gestion-produits-uploads
    tag: latest

# Database configuration
db:
  image:
    repository: mysql
    tag: "8.0"
  resources:
    limits:
      memory: "1024Mi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
  rootPassword: "root"
  database: "gestion_produits"
  rootHost: "%"
  # Database configuration
  configuration: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    default_authentication_plugin=mysql_native_password
    max_connections=1000
    max_allowed_packet=256M
    innodb_buffer_pool_size=512M
    innodb_log_file_size=256M
    innodb_log_buffer_size=8M
    innodb_flush_log_at_trx_commit=1
    innodb_flush_method=O_DIRECT
    
  # Database healthcheck configuration
  healthcheck:
    enabled: true
    livenessProbe:
      initialDelaySeconds: 120  # Increased initial delay
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 90  # Increased initial delay
      periodSeconds: 10
      timeoutSeconds: 5  # Increased timeout
      successThreshold: 1
      failureThreshold: 10  # Increased failure threshold
    startupProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30  # Allow up to 5 minutes for startup (30 * 10s)

# Persistence configuration
persistence:
  storageClass: longhorn
  db:
    size: 5Gi
  uploads:
    size: 2Gi

# Ingress configuration
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: gestion-produits-masset.germainleignel.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gestion-produits-tls
      hosts:
        - gestion-produits-masset.germainleignel.com

# Certificate configuration
certificate:
  enabled: true
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: gestion-produits-tls
  dnsNames:
    - gestion-produits-masset.germainleignel.com

# KEDA autoscaling configuration
keda:
  enabled: true
  scaling:
    minReplicas: 1
    maxReplicas: 5  # Start with a conservative max to avoid over-provisioning
    cpu:
      enabled: true
      targetUtilization: 70  # Scale up when CPU reaches 70%
    prometheus:
      enabled: true
      # kube-prometheus-stack typically exposes Prometheus at this address
      serverAddress: "http://prometheus-operated.monitoring.svc:9090"
      # Query for HTTP request rate
      query: 'sum(rate(nginx_ingress_controller_requests{exported_service=~"{{ .Release.Name }}-app"}[2m]))'
      threshold: "10"  # Scale up when request rate exceeds 10 req/s
      # Add authentication if your Prometheus requires it
      # authModes: ["bearer"]
      # bearerToken: "your-bearer-token"  # Optional: Only needed if Prometheus requires authentication

# Grafana dashboard configuration
grafana:
  dashboard:
    enabled: true